-- Create contact_leads table if it doesn't exist
CREATE TABLE IF NOT EXISTS contact_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'new',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable realtime for the table
alter publication supabase_realtime add table contact_leads;

-- Create RLS policy for the table (disabled by default)
DROP POLICY IF EXISTS "Allow full access" ON contact_leads;
CREATE POLICY "Allow full access"
ON contact_leads
FOR ALL
USING (true);
